from django.db import models

# Create your models here.
class Initiative(models.Model):
	ag_id = models.CharField(max_length=10)
	id_note = models.CharField(max_length=50)
	sos_id = models.CharField(max_length=10)
	title = models.CharField(max_length=999)
	summary = models.CharField(max_length=9999)
	proponent = models.CharField(max_length=200)
	email = models.CharField(max_length=200)
	phone = models.CharField(max_length=20)
	date_sum = models.DateTimeField('Summary Date')
	status = models.CharField(max_length=50)
	date_circulation_deadline = models.DateTimeField('Circulation Deadline')
	sigs_req = models.IntegerField(default=0)
	date_qualified = models.DateTimeField('Date Qualified')
	date_failed = models.DateTimeField('Date Failed to Qualify')
	date_sample_due = models.DateTimeField('Date Random Sample Due')
	date_raw_count_due = models.DateTimeField('Date Raw Count Due')
	election = models.CharField(max_length=200)
	prop_num = models.CharField(max_length=10)
	full_text_link = models.CharField(max_length=200)
	sig_count_link = models.CharField(max_length=200)
	fiscal_impact_link = models.CharField(max_length=200)
